'use strict';
(() => {
const {services, logos, partners, articles} = window.NEXAGEN_CONTENT;
const main = document.getElementById('main');
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logoImage = logo => `src="${escape(logo.image)}"${logo.imageRetina?` srcset="${escape(encodeURI(decodeURIComponent(logo.image)))} 1x, ${escape(encodeURI(decodeURIComponent(logo.imageRetina)))} 2x"`:''}`;
const clientWebsiteOverlay = client => client.website ? `<a class="client-website-overlay" href="${escape(client.website)}" target="_blank" rel="noopener noreferrer" aria-label="Open ${escape(client.name)} website or portal (new tab)" title="Open ${escape(client.name)} website or portal"><span aria-hidden="true">↗</span></a>` : '';
const button = (text, href, secondary=false) => `<a class="button${secondary?' secondary':''}" href="${escape(href)}">${escape(text)} <span aria-hidden="true">↗</span></a>`;
const head = (label,title,description='') => `<div class="section-head"><div><span class="eyebrow">${escape(label)}</span><h2>${escape(title)}</h2>${description?`<p>${escape(description)}</p>`:''}</div></div>`;
const intro = (label,title,description='') => `<section class="page-intro container"><span class="eyebrow">${escape(label)}</span><h1>${escape(title)}</h1><p>${escape(description)}</p></section>`;
const section = (content, cls='') => `<section class="section ${cls}"><div class="container">${content}</div></section>`;
const cta = () => section(`<div class="cta-inner"><div><span class="eyebrow">YOUR NEXT CHAPTER</span><h2>Let’s make technology work for your business.</h2><p>Bring your idea, your challenge, or the system you want to improve.</p></div>${button('Discuss Your Project','#/contact')}</div>`,'white');
const serviceCards = items => `<div class="grid">${items.map((s,i)=>`<article class="card"><span class="card-number">${String(i+1).padStart(2,'0')} / SOLUTIONS</span><h3>${escape(s.title)}</h3><p>${escape(s.description)}</p><a class="text-link" href="#/services/${s.slug}">Explore service <span aria-hidden="true">↗</span></a></article>`).join('')}</div>`;
const logoCards = items => `<div class="grid">${items.map(l=>`<figure class="logo-card">${clientWebsiteOverlay(l)}<img ${logoImage(l)} alt="${escape(l.name)} logo" width="260" height="130" loading="lazy" decoding="async"><figcaption><a class="client-name-link" href="${clientHref(l)}">${escape(l.name)} <span aria-hidden="true">↗</span></a><span class="client-category">${escape(l.category)}</span></figcaption></figure>`).join('')}</div>`;
const faq = (items,id='') => `<div class="faq" ${id?`id="${id}"`:''}>${items.map(([q,a])=>`<details><summary>${escape(q)}</summary><p>${escape(a)}</p></details>`).join('')}</div>`;
const process = () => `<div class="process-grid">${[
['Discover & plan','We understand your workflows, users and priorities, then define a practical scope and milestones.'],
['Design & develop','We shape the user experience and build the agreed features with regular opportunities for feedback.'],
['Test & launch','We review functionality, usability and responsive layouts before preparing the release.'],
['Support & improve','We agree on documentation, handover and the ongoing support your solution needs.']
].map(([t,d],i)=>`<article class="process-item"><span>0${i+1}</span><h3>${t}</h3><p>${d}</p></article>`).join('')}</div>`;
const teamCards = () => `<div class="grid team-grid">${partners.map(p=>`<article class="team-card"><img src="${escape(p.photo)}" alt="${escape(p.name)}" width="400" height="310" loading="lazy" decoding="async"><div class="team-copy"><h3>${escape(p.name)}</h3><p>${escape(p.role)}</p><details class="partner-details"><summary aria-label="Toggle partner details"><span class="partner-details-label">Partner details</span><span aria-hidden="true">+</span></summary><p>${escape(p.responsibility)}</p></details></div></article>`).join('')}</div>`;
const clientHref = client => `#/portal/client/${encodeURIComponent(client.name)}`;
const featuredClients = () => `<div class="featured-client-grid">${[logos[0],logos[1],logos.find(l=>l.name==='Afino Textile Mills'),logos.find(l=>l.name==='Tulips')].map((client,i)=>`<article class="featured-client"><div class="client-art">${clientWebsiteOverlay(client)}<img ${logoImage(client)} alt="${escape(client.name)} logo" width="480" height="240" loading="lazy" decoding="async"><span class="client-art-caption">CLIENT IDENTITY / ${escape(client.category.toUpperCase())}</span></div><div class="featured-client-copy"><span class="eyebrow">${escape(client.category)} · CLIENT PROFILE</span><h3>${escape(client.name)}</h3><p>${client.category==='Travel'?'A travel brand represented in our client portal.':'A business represented in our client portal.'}</p><a class="text-link" href="${clientHref(client)}">Explore client profile <span aria-hidden="true">↗</span></a></div></article>`).join('')}</div>`;
const partnerSection = () => section(head('THE PEOPLE BEHIND NEXAGEN','Our partners.','Meet the people behind Nexagen Solution.')+teamCards());
function partnersPage(){return intro('Partners','People behind the possibilities.','Meet the partners behind Nexagen Solution, our client relationships and our approach to technology.')+partnerSection()+cta();}
function clientProfile(client){return intro('Client portal',client.name,`${client.category} · Client profile`)+section(`<div class="split"><div class="client-profile-art">${clientWebsiteOverlay(client)}<img ${logoImage(client)} alt="${escape(client.name)} logo" width="600" height="360"></div><div><span class="eyebrow">CLIENT IDENTITY</span><h2>A name in our client portal.</h2><p>${escape(client.name)} is represented in the existing Nexagen Solution client collection.</p><p>This profile presents the supplied client identity. It does not claim a specific project scope, technology stack, result or endorsement.</p><div class="actions">${button('Discuss a similar business need','#/contact')}${button('All clients','#/portal',true)}</div></div></div>`,'white')+section(head('PROJECT INFORMATION','Start with a conversation.','Speak with our team about the scope and examples relevant to your own project. Detailed project documentation and approved case studies are not currently published here.')+button('Explore services','#/services',true))+cta();}
const commonFaq = [
['How do we start a project?','Share your goals and current challenges through our inquiry form, by email or on WhatsApp. We can then discuss the scope and next steps.'],
['Can you improve an existing website or system?','Yes. Tell us what is working, what needs improvement, and any constraints so we can assess a suitable approach.'],
['How long does a project take?','The timeline depends on scope, integrations and feedback. Milestones and a delivery schedule are agreed after requirements are reviewed.'],
['What about maintenance and support?','Maintenance and technical support are existing service offerings. Availability, scope and response arrangements should be agreed for your project.'],
['Who owns the finished work?','Ownership, source-code access, third-party licenses and handover requirements should be documented in the project agreement.'],
['Do you support travel businesses?','Our existing offerings include travel portals, hotel websites, group booking and Umrah package booking systems.']];
function home(){return `<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">NEXAGEN SOLUTION / DIGITAL & BUSINESS TECHNOLOGY</span><h1>Better systems.<br><span>New possibilities.</span></h1><p>We turn business challenges into practical software, websites and mobile experiences. Thoughtfully designed. Built around the way you work.</p><div class="actions">${button('Explore Our Work','#/portal')}${button('Discuss Your Project','#/contact',true)}</div><div class="strengths"><span>Custom development</span><span>Business systems</span><span>Travel technology</span></div></div><div class="hero-art"><div class="visual-topline"><span>FROM IDEA TO EVERYDAY IMPACT</span><span aria-hidden="true">↗</span></div><img src="assets/it company-no-bg.svg" alt="Team collaborating on digital solutions" width="560" height="340" fetchpriority="high"><div class="visual-caption"><span>PEOPLE. PROCESS. TECHNOLOGY.</span><span>BUILT AROUND YOU</span></div></div></div></section>
<div class="brand-strip"><div class="container brand-strip-inner"><p>CLIENT PORTAL<br><strong>Across travel and business</strong></p><div class="logo-row">${logos.slice(0,3).map(l=>`<a href="#/portal" aria-label="Explore the client portal: ${escape(l.name)}"><img ${logoImage(l)} alt="${escape(l.name)}" width="130" height="62"></a>`).join('')}</div></div></div>
${section(head('THE CLIENT PORTAL','Different businesses. Shared possibilities.','Discover a selection of client identities from our travel and business portal. Client profiles are distinct from project case studies.')+featuredClients()+`<div class="actions">${button('Explore the full client portal','#/portal',true)}</div>`,'white')}
${section(head('OUR EXPERTISE','The right tools. A better way forward.','Build a clearer online presence, simplify a business process or bring your next digital idea to life.')+serviceCards([services[0],services[1],services[2],services[14],services[15],services[16]])+`<div class="actions">${button('View all services','#/services',true)}</div>`)}
${section(`<div class="split"><div><span class="eyebrow">WHY NEXAGEN</span><h2>Good technology starts with understanding your business.</h2><p>We work with you to make the requirements clear, keep the user experience practical and shape a solution around your day-to-day operations.</p>${button('Our approach','#/about',true)}</div><div class="principles">${[['Your needs come first','Requirements gathering and collaboration guide the scope before development begins.'],['Clear steps, shared progress','Defined milestones give you opportunities to review work and provide feedback.'],['Care beyond the interface','Testing, documentation and a considered handover help your team use the finished solution.']].map(([t,d])=>`<article class="principle"><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></div>`,'dark')}
${section(head('HOW WE WORK','A clear path from idea to launch.')+process(),'white')}
${partnerSection()}
${section(head('COMMON QUESTIONS','A little clarity before we begin.')+faq(commonFaq,'faq'),'white')}${cta()}`;}
function about(){return intro('About Us','Technology with purpose.','Nexagen Solution is a software development company focused on tailor-made digital solutions and real business problems.')+
section(`<div class="split"><div><span class="eyebrow">OUR APPROACH</span><h2>Software should adapt to your needs.</h2><p>We build custom software, ERP and business solutions, accounting and inventory software, websites and mobile applications. Our approach starts with understanding your business, your challenges and your goals.</p><p>Our mission is to make business technology simpler to use and useful in everyday work.</p>${button('Meet us about your project','#/contact')}</div><div class="card"><h3>Principles that guide our work</h3><ul><li>Understand the people and processes behind the request.</li><li>Define scope and communicate openly.</li><li>Design clear, usable experiences.</li><li>Review quality throughout development.</li><li>Plan a practical handover and support approach.</li></ul></div></div>`,'white')+
partnerSection()+
section(head('OUR DELIVERY APPROACH','Built together, step by step.')+process(),'white')+section(head('OUR OFFICE','Let’s start a conversation.','Office No. 1220, 2nd Floor Ali Mall, Susan Road, Faisalabad, Pakistan.')+button('Contact our team','#/contact'))+cta();}
function serviceDetail(s){return intro('Services',s.title,s.description)+section(`<div class="split"><div><span class="eyebrow">A SOLUTION SHAPED AROUND YOU</span><h2>Start with the problem you want to solve.</h2><p>${escape(s.description)} We begin by reviewing your existing process, your users and the priorities for your project.</p><h3>Is this right for your business?</h3><p>This service is a starting point for businesses exploring ${escape(s.title.toLowerCase())}. Bring your current tools, pain points and desired workflow so we can assess the fit.</p></div><div class="card"><h3>Plan the scope together</h3><p>The items below are discussion points; implementation depends on your agreed project scope.</p><ul><li>Key user journeys and essential features</li><li>Existing data and systems to connect</li><li>Usability and device requirements</li><li>Testing, documentation and handover</li><li>Maintenance and support arrangements</li></ul>${button('Request a Consultation',`#/contact?service=${s.slug}`)}</div></div>`,'white')+section(head('PLAN YOUR PROJECT','What we’ll discuss together.')+`<div class="grid">${s.planningQuestions.map((question,i)=>`<article class="card"><span class="card-number">0${i+1} / DISCOVERY</span><h3>${escape(question)}</h3><p>The answer helps us define suitable deliverables and an agreed project scope.</p></article>`).join('')}</div>`)+section(head('DELIVERY','A clear path forward.')+process())+section(head('SERVICE QUESTIONS','Before we build.')+faq([[`What is included in ${s.title}?`,'We define deliverables after reviewing your requirements. Any integrations, licenses, data migration and ongoing support should be included explicitly in the proposal.'],['Can this connect to our existing systems?','Share the systems, available APIs and access requirements. Compatibility needs to be assessed before integration is agreed.'],['How can I see relevant work?','Browse the existing client portal or ask the team for approved examples. The site does not currently include verified case-study scopes or outcomes.']])+`<div class="actions">${button('Browse portal','#/portal',true)}</div>`,'white')+cta();}
let portfolioCategory='All',portfolioLimit=12;
function searchPage(){return intro('Search','Find your next step.','Search service offerings, existing client names and draft editorial topics.')+section(`<div class="toolbar"><label for="siteSearch">Search the website<input id="siteSearch" type="search" placeholder="Try websites, inventory or a client name"></label><button class="button secondary" type="button" id="clearSearch">Clear</button></div><p class="result-count" id="searchCount" role="status"></p><div class="grid" id="searchResults"></div>`,'white');}
function setupSearch(){const input=document.getElementById('siteSearch');const collection=[...services.map(s=>({title:s.title,description:s.description,kind:'Service',href:`#/services/${s.slug}`})),...logos.map(l=>({title:l.name,description:`${l.category} client logo from the existing portal.`,kind:'Portal',image:l.image,imageRetina:l.imageRetina,href:`#/portal?client=${encodeURIComponent(l.name)}`})),...articles.map(a=>({title:a.title,description:a.description||'Draft for owner review.',kind:'Editorial draft',href:`#/blog/${a.slug}`}))];function update(){const query=input.value.trim().toLowerCase();const found=query?collection.filter(x=>`${x.title} ${x.description}`.toLowerCase().includes(query)):[];document.getElementById('searchCount').textContent=query?`${found.length} result${found.length===1?'':'s'} found${found.length?'':'. Try another search.'}`:'Enter a service, topic or client name to search.';document.getElementById('searchResults').innerHTML=found.slice(0,30).map(x=>`<article class="card">${x.image?`<div class="search-result-art"><img ${logoImage(x)} alt="${escape(x.title)} logo" width="280" height="140" loading="lazy" decoding="async"></div>`:''}<span class="eyebrow">${escape(x.kind)}</span><h2 style="font-size:21px">${escape(x.title)}</h2><p>${escape(x.description)}</p><a class="text-link" href="${escape(x.href)}">View result ↗</a></article>`).join('');if(found.length>30)document.getElementById('searchCount').textContent+=' Showing the first 30. Refine your search for more specific results.';}input.addEventListener('input',update);document.getElementById('clearSearch').addEventListener('click',()=>{input.value='';update();input.focus();});update();}
function portalGallery(){const featured=[logos[0],logos[1],logos.find(l=>l.name==='Afino Textile Mills'),logos.find(l=>l.name==='Tulips')];const selected=[...featured,...logos.filter(client=>!featured.includes(client))];return `<section class="portal-gallery" aria-label="Explore client connections"><div class="container portal-gallery-heading"><span class="eyebrow">NEXAGEN / CLIENT COLLECTION</span><h1>Our clients.<br>Shared possibilities<span>.</span></h1><div class="portal-gallery-description"><p>Explore the brands in our network.<br>Travel, business and beyond.</p><div class="portal-view-actions"><button type="button" class="portal-view-toggle portal-directory-link" aria-pressed="false">Simple view</button><button type="button" class="portal-directory-link portal-browse">Browse all clients &#8599;</button></div></div></div><div class="portal-track">${selected.map((client,i)=>`<a class="portal-record" href="${clientHref(client)}"><span class="portal-record-index">${String(i+1).padStart(2,'0')} / ${escape(client.category.toUpperCase())}</span><div class="portal-box portal-box-${i%4}"><span class="portal-box-label">CLIENT COLLECTION <span aria-hidden="true">&#8599;</span></span><img ${logoImage(client)} alt="${escape(client.name)} logo" width="340" height="170" loading="lazy" decoding="async"><span class="portal-box-caption">Explore client profile</span></div><span class="portal-record-name">${escape(client.name)} <span aria-hidden="true">&#8599;</span></span></a>`).join('')}</div><div class="container portal-gallery-footer"><span>SWIPE / SCROLL TO EXPLORE <span aria-hidden="true">&#8594;</span></span><div class="portal-progress" aria-hidden="true"><span class="portal-progress-fill"></span></div><span>${String(selected.length).padStart(2,'0')} CONNECTIONS</span></div></section>`;}
function portal(){return portalGallery()+section(head('CLIENT CONNECTIONS','Our Top Clients','Meet the businesses we’re proud to work with, building strong connections across travel and other industries.')+featuredClients(),'white portal-featured')+section(`<div id="portalDirectory"></div>${head('ALL CLIENTS','Find a familiar name.','Browse the supplied client logos by category. For project scope and examples, speak with our team.')}<div class="filters" aria-label="Filter portal">${['All','Travel','Other businesses'].map(c=>`<button type="button" data-category="${c}" aria-pressed="${c===portfolioCategory}">${c}</button>`).join('')}</div><p id="portfolioCount" class="result-count" role="status"></p><div id="portfolioGrid"></div><div class="actions"><button id="loadClients" class="button secondary" type="button">Show more clients</button></div>`,'white')+cta();}
function updatePortfolio(){const filtered=logos.filter(l=>portfolioCategory==='All'||l.category===portfolioCategory).sort((a,b)=>Number(Boolean(b.website))-Number(Boolean(a.website)));document.getElementById('portfolioGrid').innerHTML=logoCards(filtered.slice(0,portfolioLimit));document.getElementById('portfolioCount').textContent=`Showing ${Math.min(portfolioLimit,filtered.length)} of ${filtered.length} clients`;document.getElementById('loadClients').hidden=portfolioLimit>=filtered.length;document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.category===portfolioCategory)));}
const blogCard = a => {
const i=articles.indexOf(a);
return `<article class="card insight-card"><div class="blog-art blog-art-${i}" aria-hidden="true"><span>${['↗','⌘','◇','◎','☁','▧','→'][i%7]}</span><span>${escape(a.category)}<br>Nexagen insights</span></div><div class="insight-meta"><span class="eyebrow">${escape(a.category)}</span><span class="insight-status">Draft ${a.body?'article':'planning guide'}</span></div><h3><a href="#/blog/${a.slug}">${escape(a.title)}</a></h3><p>${escape(a.description||'A practical introduction to planning technology around everyday business needs.')}</p><a class="text-link" href="#/blog/${a.slug}">${a.body?'Read article preview':'Explore planning guide'} <span aria-hidden="true">↗</span></a></article>`;
};
function blog(){return intro('Insights','Ideas that move your business forward.','Explore practical topics about websites, business software and digital growth. Find a useful starting point for your next project.')+section(`<div class="insights-intro"><div><span class="eyebrow">EXPLORE THE IDEAS</span><h2>A clearer path to better digital work.</h2><p>Browse article previews and planning guides from Nexagen Solution.</p></div><span class="insight-status">Editorial drafts</span></div><div class="toolbar insights-toolbar"><label for="blogSearch">Search insights<input id="blogSearch" type="search" placeholder="Search a topic or keyword"></label><label for="blogCategory">Category<select id="blogCategory"><option>All</option>${[...new Set(articles.map(a=>a.category))].map(c=>`<option>${escape(c)}</option>`).join('')}</select></label><button class="button secondary" type="button" id="clearBlog">Clear filters</button></div><p id="blogCount" class="result-count" role="status"></p><div class="grid insights-grid" id="blogGrid"></div>`,'white')+cta();}
function updateBlog(){const query=document.getElementById('blogSearch').value.toLowerCase().trim();const category=document.getElementById('blogCategory').value;const found=articles.filter(a=>(category==='All'||a.category===category)&&`${a.title} ${a.description||''} ${a.category}`.toLowerCase().includes(query));document.getElementById('blogCount').textContent=found.length?`${found.length} insight${found.length===1?'':'s'} found`:'No matching insights. Try another keyword or clear the filters.';document.getElementById('blogGrid').innerHTML=found.length?found.map(blogCard).join(''):'<div class="insights-empty"><h3>No insights found</h3><p>Try a broader keyword or choose another category.</p></div>';}
function article(a){const content=a.body||`<p class="reader-intro">${escape(a.description)}</p><h2>Questions to shape your project</h2><p>Use these prompts to prepare a focused discussion with your team.</p><ul class="planning-questions">${(a.planningQuestions||[]).map(q=>`<li>${escape(q)}</li>`).join('')}</ul><h2>Plan your next step</h2><p>Bring your goals, current challenges and answers to these questions to an initial project discussion.</p>`;return intro('Insights',a.title,a.body?'An article preview about making technology work for your business.':'A planning guide to help you ask the right questions.')+section(`<article class="reading insight-reading"><div class="insight-meta"><span class="eyebrow">${escape(a.category)}</span><span class="insight-status">Editorial draft</span></div>${content}<div class="actions">${button('Back to insights','#/blog',true)}${button('Discuss your project','#/contact')}</div><h2>Keep exploring</h2><div class="related-insights">${articles.filter(x=>x!==a).slice(0,3).map(x=>`<a href="#/blog/${x.slug}"><span class="eyebrow">${escape(x.category)}</span><strong>${escape(x.title)}</strong><span aria-hidden="true">↗</span></a>`).join('')}</div></article>`,'white');}
let inquiryDraft={};
const field = (name,title,type='text',required=false,full=false)=>`<label class="${full?'full':''}" for="${name}">${title}${required?' *':' <small>(optional)</small>'}<input id="${name}" name="${name}" type="${type}" ${required?'required':''} maxlength="${type==='email'?254:120}" autocomplete="${{name:'name',email:'email',phone:'tel',company:'organization'}[name]||'off'}" aria-describedby="${name}Error"><span class="error" id="${name}Error"></span></label>`;
function contact(){return intro('Contact','Tell us what’s next.','A new idea, a better workflow, or a system that needs attention. Let’s discuss the right next step.')+section(`<div class="contact-grid"><div class="contact-details"><h2>Talk to our team</h2><p>Email or message us on WhatsApp to discuss your project.</p><a href="https://wa.me/923226069003" target="_blank" rel="noopener noreferrer">+92 322 6069003</a><a href="https://wa.me/923037682000" target="_blank" rel="noopener noreferrer">+92 303 7682000</a><a href="mailto:info@nexagensolution.com">info@nexagensolution.com</a><a href="mailto:contact@nexagensolution.com">contact@nexagensolution.com</a><h2>Visit our office</h2><p>Office No. 1220, 2nd Floor Ali Mall,<br>Susan Road, Faisalabad, Pakistan.</p><a href="https://www.google.com/maps?q=31.4261877,73.1217697&z=17" target="_blank" rel="noopener noreferrer">Open in Maps ↗</a><p>Office hours: Monday–Friday, 9AM–6PM. Call ahead to arrange a visit.</p><button class="button secondary" type="button" id="loadMap">Load office map</button><div id="mapSlot"></div><p class="content-gap">Loading the map connects to Google Maps.</p></div>
<div class="form-card"><h2>Discuss your project</h2><p>No registration needed. Required fields are marked *. This form prepares an inquiry for WhatsApp or your email app. You must review and send it there; this website cannot confirm delivery.</p><form id="contactForm" novalidate><div class="form-grid">${field('name','Your name','text',true)}${field('email','Email','email',true)}${field('phone','Phone','tel')}${field('company','Company')}
<label class="full" for="service">Service of interest<select name="service" id="service"><option value="">Not sure yet</option>${services.map(s=>`<option value="${s.slug}">${escape(s.title)}</option>`).join('')}</select></label>
<label for="budget">Budget <small>(optional)</small><select id="budget" name="budget"><option>Not sure yet</option><option>Discuss a budget with the team</option><option>I have a budget in mind</option></select></label><label for="timeline">Preferred timeline <small>(optional)</small><input id="timeline" name="timeline" maxlength="120" placeholder="For example: within three months"></label>
<label class="full" for="message">Project description *<textarea id="message" name="message" required minlength="20" maxlength="5000" rows="5" aria-describedby="messageError" placeholder="Your goals, current challenges and what you would like to build."></textarea><span class="error" id="messageError"></span></label>
</div><p class="content-gap">Your inquiry stays in this browser tab until you choose a handoff. See our <a href="#/privacy">draft privacy information</a>.</p><div class="actions"><button class="button" type="submit">Prepare WhatsApp inquiry ↗</button><button class="button secondary" id="emailInquiry" type="button">Prepare email</button></div><div id="formStatus" class="form-status" role="status" aria-live="polite"></div></form></div></div>`,'white')+section(head('WHAT HAPPENS NEXT','A conversation, then a clear plan.')+process())+section(`<details><summary class="text-link">Your saved visitor feedback</summary><p>Feedback from the earlier site is stored only in this browser. It is not submitted to Nexagen or shown to other visitors.</p><form id="feedbackForm"><label>Your name<input name="name" required maxlength="120"></label><label>Role or company (optional)<input name="role" maxlength="120"></label><label>Your feedback<textarea name="feedback" required maxlength="5000"></textarea></label><button class="button" type="submit">Save in this browser</button><p id="feedbackStatus" role="status"></p></form><div id="feedbackList" class="feedback-list"></div></details>`)+cta();}
function legal(kind){const privacy=kind==='privacy';return intro(privacy?'Privacy draft':'Terms draft',privacy?'Privacy information — draft':'Website terms — draft','Owner review required before these documents can be treated as final company policies.')+section(`<article class="reading"><div class="notice">Draft based on this website’s current features. The company must review contact details, retention periods, contractual terms and applicable requirements before publication.</div>${privacy?`<h2>Inquiries</h2><p>The inquiry form holds your details in the current browser tab. It does not submit to a website backend. Choosing a handoff opens WhatsApp or your email application so you can review and send the message. Those providers apply their own privacy terms.</p><h2>Local visitor feedback</h2><p>The optional feedback feature stores your name, role and feedback in this browser’s local storage. It is not shared with other visitors or Nexagen. You can edit or remove saved entries from the Contact page. Earlier local feedback is preserved.</p><h2>Third-party services</h2><p>WhatsApp, email, social links and the optional Google Maps embed connect to outside services when used. This version adds no analytics, marketing tracking or subscription service.</p><h2>Owner review items</h2><p>The company must document how it handles inquiries after receipt, retention periods and requests about personal information. Contact info@nexagensolution.com for questions.</p>`:`<h2>Information on this site</h2><p>Services are descriptions of offerings supplied with the existing website. Specific capabilities, costs, timelines, licenses and support must be agreed for each project.</p><h2>Draft editorial content</h2><p>Blog drafts and topic outlines are for review. They are not presented as published company guidance or contractual commitments.</p><h2>External destinations</h2><p>Links to messaging, maps and social services are provided for convenience. The relevant service’s terms apply when you use it.</p><h2>Project agreements</h2><p>Written agreements should define deliverables, payment, intellectual property, data responsibilities, handover, maintenance and dispute handling. This website does not establish those terms.</p><h2>Owner review items</h2><p>Confirm the company’s legal identity, jurisdiction, contractual terms and contact information before adopting a final policy.</p>`}</article>`,'white');}
function notFound(){return intro('Page not found','This page is still to be found.','The link may be incomplete or the page may have moved.')+section(button('Return Home','#/home')+` <a class="text-link" href="#/services">Explore services</a>`,'white');}
const menu=document.getElementById('navLinks'),toggle=document.getElementById('menuToggle');
function closeMenu(restore=false){menu.classList.remove('open');toggle.setAttribute('aria-expanded','false');if(restore)toggle.focus();}
toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));if(open)menu.querySelector('a').focus();});
const help=document.getElementById('helpPanel'),helpToggle=document.getElementById('helpToggle');
function closeHelp(restore=false){help.hidden=true;helpToggle.setAttribute('aria-expanded','false');if(restore)helpToggle.focus();}
helpToggle.addEventListener('click',()=>{const open=help.hidden;help.hidden=!open;helpToggle.setAttribute('aria-expanded',String(open));if(open)document.getElementById('helpClose').focus();});
document.getElementById('helpClose').addEventListener('click',()=>closeHelp(true));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!help.hidden)closeHelp(true);else if(menu.classList.contains('open'))closeMenu(true);}});
document.addEventListener('click',e=>{if(!e.target.closest('.navigation'))closeMenu();if(!e.target.closest('.floating-tools'))closeHelp();if(e.target.closest('#helpPanel a'))closeHelp();});
document.getElementById('year').textContent=new Date().getFullYear();
function captureDraft(){const form=document.getElementById('contactForm');if(form)inquiryDraft=Object.fromEntries(new FormData(form));}
function render(initial=false){window.portalMotion?.destroy();captureDraft();const raw=location.hash.replace(/^#\/?/,'')||'home';const [path,query='']=raw.split('?');const [rawPage,slug,detail]=path.split('/');const page=rawPage==='portfolio'?'portal':rawPage;let clientName='';try{clientName=decodeURIComponent(detail||'');}catch{}const params=new URLSearchParams(query);let title,description,markup,noindex=false;
if(page==='home'){title='Software & Travel Technology';description='Websites, software and mobile applications that simplify everyday work.';markup=home();}
else if(page==='about'){title='About Us';description='Meet Nexagen Solution and our approach to business technology.';markup=about();}
else if(page==='services'&&!slug){title='Services';description='Explore custom software, websites, business systems and travel technology.';markup=intro('Services','The right tools for your business.','Every project begins with a discussion of your needs and an agreed scope. Explore the right starting point for your business.')+section(serviceCards(services),'white')+cta();}
else if(page==='services'&&services.some(s=>s.slug===slug)){const s=services.find(s=>s.slug===slug);title=s.title;description=s.description;markup=serviceDetail(s);}
else if(page==='search'){title='Search';description='Find services, client logos and editorial topics.';markup=searchPage();noindex=true;}
else if(page==='partners'&&!slug){title='Partners';description='Meet the five partners behind Nexagen Solution.';markup=partnersPage();}
else if(page==='portal'&&slug==='client'&&logos.some(l=>l.name===clientName)){const client=logos.find(l=>l.name===clientName);title=client.name+' | Client Portal';description='Client identity from the Nexagen Solution portal.';markup=clientProfile(client);}
else if(page==='portal'&&!slug){title='Portal';description='Client logos from Nexagen Solution’s existing travel and business portal.';markup=portal();}
else if(page==='blog'&&!slug){title='Insights';description='Explore practical article previews and planning guides for your next digital project.';markup=blog();noindex=true;}
else if(page==='blog'&&articles.some(a=>a.slug===slug)){const a=articles.find(a=>a.slug===slug);title=a.title;description='Draft article for company review.';markup=article(a);noindex=true;}
else if(page==='contact'){title='Contact & Project Inquiry';description='Discuss a project with Nexagen Solution in Faisalabad.';markup=contact();}
else if(['privacy','terms'].includes(page)){title=page==='privacy'?'Privacy Draft':'Terms Draft';description='Draft website information for owner review.';markup=legal(page);noindex=true;}
else{title='Page Not Found';description='Find your way back to Nexagen Solution.';markup=notFound();noindex=true;}
main.innerHTML=markup;document.title=`${title} | Nexagen Solution`;document.querySelector('meta[name=description]').content=description;document.querySelector('meta[property="og:title"]').content=document.title;document.querySelector('meta[property="og:description"]').content=description;
let robots=document.querySelector('meta[name=robots]');if(!robots){robots=document.createElement('meta');robots.name='robots';document.head.append(robots);}robots.content=noindex?'noindex,follow':'index,follow';
document.querySelectorAll('.nav-links a').forEach(a=>{if(a.hash===`#/${page}`)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});closeMenu();closeHelp();
if(page==='portal'&&!slug){updatePortfolio();document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{portfolioCategory=b.dataset.category;portfolioLimit=12;updatePortfolio();}));document.getElementById('loadClients').addEventListener('click',()=>{portfolioLimit+=12;updatePortfolio();});}
if(page==='blog'&&!slug){updateBlog();document.getElementById('blogSearch').addEventListener('input',updateBlog);document.getElementById('blogCategory').addEventListener('change',updateBlog);document.getElementById('clearBlog').addEventListener('click',()=>{document.getElementById('blogSearch').value='';document.getElementById('blogCategory').value='All';updateBlog();document.getElementById('blogSearch').focus();});}
main.querySelectorAll('.team-card').forEach(card=>{const details=card.querySelector('.partner-details');card.addEventListener('pointerenter',event=>{if(event.pointerType==='mouse')details.open=true;});card.addEventListener('pointerleave',event=>{if(event.pointerType==='mouse'&&!details.dataset.pinned&&!card.contains(document.activeElement))details.open=false;});card.addEventListener('focusout',()=>{queueMicrotask(()=>{if(!details.dataset.pinned&&!card.matches(':hover')&&!card.contains(document.activeElement))details.open=false;});});details.querySelector('summary').addEventListener('click',event=>{event.preventDefault();const pinned=details.dataset.pinned==='true';if(pinned){delete details.dataset.pinned;details.open=false;}else{details.dataset.pinned='true';details.open=true;}});});
if(page==='search')setupSearch();
if(page==='portal'&&!slug&&params.has('client')){const matching=logos.filter(l=>l.name===params.get('client'));document.getElementById('portfolioGrid').innerHTML=logoCards(matching);document.getElementById('portfolioCount').textContent=`${matching.length} matching client${matching.length===1?'':'s'} found. Choose a category to browse the full portal.`;document.getElementById('loadClients').hidden=true;}
if(page==='blog'&&!slug&&params.has('q')){document.getElementById('blogSearch').value=params.get('q');updateBlog();}
if(page==='contact')setupContact(params);
main.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.hidden=true;const fallback=document.createElement('span');fallback.className='notice';fallback.textContent=`Image unavailable: ${img.alt}`;img.after(fallback);},{once:true}));
document.getElementById('pageScroll').scrollTo({top:0,behavior:'instant'});window.portalMotion?.start();if(!initial)main.focus({preventScroll:true});if(params.has('faq'))document.getElementById('faq')?.scrollIntoView();
}
function setupContact(params){const form=document.getElementById('contactForm');for(const [name,value] of Object.entries(inquiryDraft)){if(form.elements.namedItem(name))form.elements.namedItem(name).value=value;}if(params.has('service')&&services.some(s=>s.slug===params.get('service')))form.elements.service.value=params.get('service');
form.addEventListener('input',captureDraft);
function prepare(channel){const status=document.getElementById('formStatus');status.replaceChildren();let first;
for(const name of ['name','email','message']){const input=form.elements.namedItem(name);input.value=input.value.trim();const error=document.getElementById(`${name}Error`);let message='';if(!input.value)message='Please complete this required field.';else if(name==='email'&&input.validity.typeMismatch)message='Enter a valid email address.';else if(name==='message'&&input.value.length<20)message='Please add at least 20 characters about your project.';input.setAttribute('aria-invalid',String(Boolean(message)));error.textContent=message;if(message&&!first)first=input;}
if(first){status.textContent='Please review the highlighted fields.';first.focus();return;}
const data=Object.fromEntries(new FormData(form));const service=services.find(s=>s.slug===data.service)?.title||'Not sure yet';const body=[ 'Hello Nexagen Solution,', '', `Name: ${data.name}`, `Email: ${data.email}`, `Phone: ${data.phone||'Not provided'}`, `Company: ${data.company||'Not provided'}`, `Service: ${service}`, `Budget: ${data.budget}`, `Timeline: ${data.timeline||'Not specified'}`, '', 'Project description:', data.message ].join('\n');
const href=channel==='email'?`mailto:info@nexagensolution.com?subject=${encodeURIComponent('Project inquiry: '+service)}&body=${encodeURIComponent(body)}`:`https://wa.me/923226069003?text=${encodeURIComponent(body)}`;
const text=document.createElement('p');text.textContent=`Inquiry prepared. Review and send it in ${channel==='email'?'your email application':'WhatsApp'}. Nothing has been sent by this website.`;const link=document.createElement('a');link.className='button';link.href=href;link.textContent=channel==='email'?'Open email draft ↗':'Open WhatsApp draft ↗';if(channel!=='email'){link.target='_blank';link.rel='noopener noreferrer';}status.append(text,link);captureDraft();status.scrollIntoView({block:'nearest'});
}
form.addEventListener('submit',e=>{e.preventDefault();prepare('whatsapp');});document.getElementById('emailInquiry').addEventListener('click',()=>prepare('email'));
document.getElementById('loadMap').addEventListener('click',e=>{document.getElementById('mapSlot').innerHTML='<iframe class="map" src="https://maps.google.com/maps?q=31.4261877,73.1217697&z=17&output=embed" title="Nexagen Solution office at Ali Mall, Susan Road, Faisalabad" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';e.target.hidden=true;});setupFeedback();}
function setupFeedback(){const key='nexagenClientFeedback';const read=()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(saved)?saved:[];}catch{return [];}};const status=document.getElementById('feedbackStatus');const save=items=>{try{localStorage.setItem(key,JSON.stringify(items));status.textContent='Saved in this browser only. Not submitted to Nexagen.';return true;}catch{status.textContent='Browser storage is unavailable. Your feedback could not be saved.';return false;}};
function draw(){const list=document.getElementById('feedbackList');list.replaceChildren();read().forEach((item,i)=>{const entry=document.createElement('article');entry.className='feedback-entry';const p=document.createElement('p');p.textContent=item.feedback;const name=document.createElement('strong');name.textContent=`${item.name}${item.role?' · '+item.role:''}`;const actions=document.createElement('div');for(const action of ['Edit','Remove']){const b=document.createElement('button');b.type='button';b.textContent=action;b.addEventListener('click',()=>{const items=read();if(action==='Remove'){items.splice(i,1);if(save(items))draw();}else{const updated=prompt('Edit your locally saved feedback:',item.feedback);if(updated?.trim()){items[i]={...item,feedback:updated.trim()};if(save(items))draw();}}});actions.append(b);}entry.append(p,name,actions);list.append(entry);});}
document.getElementById('feedbackForm').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));if(!data.name.trim()||!data.feedback.trim())return;const items=read();items.push(data);if(save(items)){form.reset();draw();}});draw();}
document.querySelectorAll('.brand, .footer-brand').forEach(link=>link.addEventListener('click',event=>{
  if(event.button!==0||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;
  event.preventDefault();
  const home=new URL(window.location.href);home.hash='/home';home.search='';
  window.history.replaceState(window.history.state,'',home.href);
  window.location.reload();
}));
window.addEventListener('hashchange',()=>render());render(true);
})();






